#!/bin/bash

#
# By Gengik84 
#


# uncomment to enable debug logging
# set -x


gscriptVer="1.0"

#
# Initialisation of a variable (our target folder).
#
tmpDirectory="/tmp/Update"

#
# Directory for unlocked combo update
#
userPath="/Users/`users`/Desktop"


###################################

function printInfo(){
  printf "\e[1m${1}\e[0;1m"
} 

function printInfo_Red(){
  printf "\e[31;1m${1}\e[0;m\n"
} 

function printInfo_Blue(){
  printf "\033[1;34;5m${1}\033[0m\n"
} 

function printInfo_Green(){
  printf "\e[32;1m${1}\e[0m\n"
}

function STY_LINE(){
  printf "%s\n\n" "-------------------------------------------------------------------------------"
}

function selectPkg(){
  read -p "Drag ComboUpdate.pkg on terminal windows and press enter: " updatePKG
    [[ ! -f "${updatePKG}" ]] && printInfo_Red "${updatePKG} not found!" && exit 1  
    
  cp -r "${updatePKG}" "${tmpDirectory}"
  STY_LINE
  printInfo_Green "Please wait...It takes a few minutes..."
}

function showBuild(){
  ver="$(cat Distribution | awk NR==12 | sed 's/<string>//' | sed 's/<\/string>//'  2>&1 )"
  comboPackage=""${ver}"_ComboUpdate_unlocked.pkg"
}

function patchDistrubutionPKG(){
  cd "${tmpDirectory}"
  pkgutil --expand *.pkg "${tmpDirectory}"/Combo
  cd "${tmpDirectory}"/Combo
  # Remove this line for use in HFS+
  perl -pi -e 's|\<volume-check script\=\"VolumeCheck\(\)\"\/\>||' Distribution
  perl -pi -e 's|\<installation\-check script\=\"InstallationCheck\(\)\"\/\>||' Distribution
}

function makePkg(){
  pkgutil --flatten "${tmpDirectory}"/Combo "${tmpDirectory}"/"${comboPackage}"
}

function endProgram(){
  printInfo_Blue "Cleaning temp files..."
  mv "${tmpDirectory}"/"${comboPackage}" "${userPath}"
  rm -rf "${tmpDirectory}" 2>/dev/null
  STY_LINE
  printInfo_Green "You can find ComboUpdate_Unlocked in ${userPath}"
  STY_LINE
}

function main(){
  rm -rf "${tmpDirectory}" 2>/dev/null
  mkdir "${tmpDirectory}" 
  
  selectPkg
  patchDistrubutionPKG
  showBuild
  makePkg
  endProgram
}

if [[ $EUID -ne 0 ]]; then
  clear
  echo "$(basename "$0" ) v:"${gscriptVer}" must be run as ROOT!"
  sudo "$0" "$@"
else
  main "$@"
fi

exit 0
